version: '3.7'

services:
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: node
    # volumes:
    #   - type: bind
    #     source: ./src/fs-data
    #     target: /data/
    #     bind:
    #       create_host_path: true
    ports:
      - 9999:5000
    restart: always
    networks:
      - app-network

  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "3000:3000"
    depends_on:
      - node
    networks:
      - app-network
  
  mongo:
    image: mongo # https://hub.docker.com/_/mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume: